---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs-client-provisioner
  labels:
    section: volume
    app: nfs-client-provisioner

---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: nfs-client-provisioner
spec:
  limits:
    - default:
        memory: 512Mi
        cpu: "0.1"
      defaultRequest:
        memory: 256Mi
        cpu: "0.1"
      max:
        memory: 2Gi
        cpu: "2"
      type: Container
