kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fluentd-forward-pvc
  namespace: logging
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
