---
include:
  - local: .gitlab-ci/default.yml
  - local: .gitlab-ci/workflow.yml
  - local: .gitlab-ci/rules.yml
  - local: .gitlab-ci/prepare.yml
  - local: .gitlab-ci/linter.yml
  - local: .gitlab-ci/test.yml
  - local: .gitlab-ci/push.yml
  - local: .gitlab-ci/deploy.yml
  - local: .gitlab-ci/create_stand.yml
  - local: .gitlab-ci/build.yml

stages:
  - prepare
  - linter
  - build
  - test
  - create_stand
  - push
  - deploy
...