---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: ingress-nginx
spec:
  limits:
    - default:
        memory: 512Mi
        cpu: "0.1"
      defaultRequest:
        memory: 256Mi
        cpu: "0.1"
      max:
        memory: 2Gi
        cpu: "2"
      type: Container