version: '3.5'
services:
  proxy:
    image: zabbix/zabbix-proxy-sqlite3:alpine-latest
    ports:
        - 10051:10051
    volumes:
        - /usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
        - /var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
        - /var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
        - /var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
        - /var/lib/zabbix/ssl/certs:/var/lib/zabbix/ssl/certs:ro
        - /var/lib/zabbix/ssl/keys:/var/lib/zabbix/ssl/keys:ro
        - /var/lib/zabbix/ssl/ssl_ca:/var/lib/zabbix/ssl/ssl_ca:ro
        - /var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
        - /var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
    restart: always
    environment:
        - ZBX_HOSTNAME=zabbix-proxy-sqlite3
        - ZBX_SERVER_HOST=192.168.0.109
        - ZBX_SERVER_PORT=10051
        - ZBX_DEBUGLEVEL=1
        - ZBX_PROXYMODE=1 # 0 - active proxy and 1 - passive proxy.
        - ZBX_CONFIGFREQUENCY=3600