Vagrant.configure("2") do |config|
    config.vm.define "nginx" do |c1|
        c1.vm.hostname = "nginx"
           
            c1.vm.provider "docker" do |d|
                d.name = "nginx"
                d.image = "nginx:latest"
                d.ports = [
                    "80:80",
                    "8080:80"
                    ]
                d.create_args = [
                    "--restart=Always",
                    "--cpus=1"
                    ]    
        end
    end

    config.vm.define "apache" do |c2|
        c2.vm.hostname = "apache"
        c2.vm.synced_folder "/tmp","/media"
            
            c2.vm.provider "docker" do |d|
                d.name = "apache"
                d.image = "httpd:latest"
                d.ports = ["8181:80"]
        end
    end

end