Vagrant.configure("2") do |config|

    config.ssh.insert_key = false

-------------RANCHER---------------

config.vm.define "rancher" do |rancher|
        rancher.vm.hostname = "rancher"
        rancher.vm.box = "ubuntu/xenial64"
        rancher.vm.network "private_network", ip: "10.10.172.10"
        rancher.vm.network "public_network", bridge: "enp7s0", ip: "192.168.0.1"
    
    rancher.vm.provider "virtualbox" do |vb|
        vb.name = "rancher"
        vb.cpus = 2
        vb.memory = "1024"
    end

    rancher.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install htop -y
        curl -fsSL https://get.docker.com/ | sh
        systemctl start docker
        systemctl enable docker
        usermod -aG docker $(whoami)
        docker images -a
        docker run -d --restart=unless-stopped -p 80:8080 rancher/server:stable
        docker images -a
    SHELL
end

---------------NFS Server---------------

config.vm.define "mynfsserver" do |mynfsserver|
    mynfsserver.vm.hostname = "mynfsserver"
    mynfsserver.vm.box = "ubuntu/xenial64"
    mynfsserver.vm.network "private_network", ip: "10.10.172.20"
    
    mynfsserver.vm.provider "virtualbox" do |vb|
        vb.name = "mynfsserver"
        vb.cpus = 1
        vb.memory = "512"
    end

    mynfsserver.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install htop nfs-kernel-server -y
        sudo mkdir /nfs
        sudo chown nobody:nogroup /nfs
        echo "/nfs *(rw,sync,no_subtree_check,no_root_squash)" > /etc/exports
        sudo systemctl restart nfs-kernel-server
    SHELL
end

---------------NODE 2---------------

config.vm.define "server2" do |server2|
    server2.vm.hostname = "server2"
    server2.vm.box = "ubuntu/xenial64"
    server2.vm.network "private_network", ip: "10.10.172.32"
    
    server2.vm.provider "virtualbox" do |vb|
        vb.name = "server2"
        vb.cpus = 2
        vb.memory = "1024"
    end

    server2.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install htop -y
        echo "10.10.172.10 rancher.int" >> /etc/hosts
        curl -fsSL https://get.docker.com/ | sh
        systemctl start docker
        systemctl enable docker
        usermod -aG docker $(whoami)
    SHELL
end
