apiVersion: v2
name: fluent-bit-art
description: Fluent-bit chart for ArgoCD
type: application
version: 0.1.0
dependencies:
- name: fluent-bit
  version: 0.21.5
  repository: https://fluent.github.io/helm-charts
