apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system-utils
  source:
    repoURL: 'https://github.com/Gordey13/devops-repo'
    path: argocd/01-clusterapp/05-logs
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
