apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.kryukovbiz: "-1001716159312"
spec:
  project: application
  source:
    repoURL: 'https://github.com/Gordey13/devops-repo'
    path: argocd/notifications/manifests/app
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
