k8s_masters:
  hosts:
    # Control nodes
    control1.gordey.local:
    control2.gordey.local:
    control3.gordey.local:
k8s_workers:
  hosts:
    # Worker nodes
    worker1.gordey.local:
    worker2.gordey.local:
    worker3.gordey.local:
    db1.gordey.local:
k8s_cluster:
  children:
    k8s_masters:
    k8s_workers:
